# Welcome to Jekyll!

# Website settings
title: "Enigma"
description: "Code, life and us."
keywords: "XIngqi_dsay,blog,Jekyll,github"
baseurl: "/"
url: "https://txqzzz.github.io"
# url: "http://127.0.0.1:4000"

# author
author:
  name: 'XIngqi_dsay'
  first_name: 'Dsay'
  last_name: 'XInQ'
  email: 'txqzzz@hotmail.com'
  facebook_username: ''
  github_username: 'txqzzz'
  head_img: 'static/img/landing/sora2.jpg'
  desciption:  'I am a student from NEU CSE, learning web development now. I love CS, maths and travelling. Life is a continuous learning process, and codes make me more rigorous, maths make me more rationla, and travel makes my life colorful. I am looking forward to a better me and better life. Still waiting for a better you.'

# sections
sections:
  - id: 'about-me'
    i18n: 'nav.about_me'
    name: 'About'
    tpl: 'about.html'
    css: ''

#  - id: 'career'
#  i18n: 'nav.career'
# name: 'Career'
# tpl: 'career.html'
# css: 'timeline'

#  - id: 'skills'
#    i18n: 'nav.skills'
#    name: 'Skills'
#    tpl: 'skills.html'
#    css: 'team'

#  - id: 'projects'
#    i18n: 'nav.projects'
#    name: 'Projects'
#    tpl: 'projects.html'
#    css: 'project'

  - id: 'blog'
    i18n: 'nav.blog'
    name: 'Blog'
    tpl: 'blog.html'
    css: 'testimonials navy-section'

#  - id: 'links'
#    i18n: 'nav.link'
#    name: 'Links'
#    tpl: 'links.html'
#    css: 'contact'

# localization
languages:
  - locale: 'en'
    flag: 'static/img/flags/United-States.png'
  - locale: 'zh'
    flag: 'static/img/flags/China.png'

# blog img path
img_path: 'http://www.jack003.com/static/img/blog'

# donate
donate:
  wechat: 'static/img/pay/wechat.png'
  alipay: 'static/img/pay/alipay.png'

# comment
changyan:
  # appid: 
  # conf: 
disqus:
  name: txqzzz
#  public_key: 

# share
bshare:
  uuid: 

# baidu analytics
ba:
  uuid: 

# google analytics
ga:
  id: UA-83536104-1

# Build settings
encoding: "utf-8"

# other settings
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: roug
paginate: 5
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
  - jekyll-paginate #


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

